In [1]:
# import numpy
# create array x

In [2]:
# 1x vector
import numpy as np
np.array([0,1,2,3])


array([0, 1, 2, 3])

In [4]:
# 2x2 matrix
np.array([[0,1],[2,3]])



array([[0, 1],
       [2, 3]])

In [8]:
# 3x3 matrix
a = np.array([[0,1,2],[3,4,5],[7,8,9]])
print a

[[0 1 2]
 [3 4 5]
 [7 8 9]]


In [7]:
a.shape

(3, 3)

In [9]:
#4 4x8 array
a = np.array([[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7],[0,1,2,3,4,5,6,7]])
a
   

array([[0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7],
       [0, 1, 2, 3, 4, 5, 6, 7]])

In [10]:
a.shape

(4, 8)

In [13]:
# add matrices
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
a + b

array([6, 6, 6, 6, 6])

In [14]:
# easier way to add matrices
a = [1,2,3]
b = [3,2,1]
np.add(a,b)

array([4, 4, 4])

In [15]:
#Set 1 - Add
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]
np.add(a,b)

array([-5, -3, -1,  1,  3,  5])

In [16]:
#Set 2 - Subtract
a = [-1, -2, -3, -4, -5, -6]
b = [-6, -5, -4, -3, -2, -1]
np.subtract(a,b)

array([ 5,  3,  1, -1, -3, -5])

In [57]:
#Set 3 - Subtract
a = [101, 201, 33.22, -423, 5.3234, -6.234]
b = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]
c = np.subtract(a,b)
print c
type(a[2])
type(c)


AttributeError: 'list' object has no attribute 'dtype'

In [33]:
#Set 4 - Subtract
a = [-101, -201, -33.22, 423, -5.3234, -34]
b = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]

for index, value in enumerate(b):
    print index,value
    if type(value) == str:
        print 'found string'
        b[index] = 0
#a.dtype = 'float'
#b.dtype = 'float'
np.subtract(a,b)
type(a)

0 601
1 -501.33
2 113
3 -3.3000003
4 l
found string
5 11.0


list

In [19]:
# ARRAY DOT PRODUCT
a = [1,2,3]
b = [4,5,6]
#  a . b = 1 x 4 =  4
#          2 x 5 = 10
#          3 x 6 = 18
#                ----
#                  32

In [48]:
#Create a 3 dimensional array
#a3 = np.array([[0,1,2],[3,4,5],[7,8,9]])
#a3 = numpy.zeros((i,j,k))
d3 = [[[0 for col in range(4)]for row in range(4)] for x in range(6)]
print d3
type(d3)
len(d3)


[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]


6

In [51]:
#Create a 5 dimensional array
d5 = [[[[[0 for col in range(3)]for row in range(3)] for x in range (3)] for z in range (2)] for y in range(2)]
print d5
len(d5)

[[[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]], [[[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]], [[[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]]]


2

In [56]:
np.empty((5, 4, 3, 2, 1))

array([[[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.]

In [2]:
# print the shape of x

In [3]:
# create a two dimensional array
a = [[0,1,2],[3,4,5]]

In [4]:
# print shape of 2d array

In [5]:
# reshape the array to 2 x 6

In [6]:
# reshape the array to 1 x 12

In [7]:
# transpose the array

In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6